yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules

npmScopes:
  croz:
    npmRegistryServer: "https://nexus.croz.net/repository/npm-all/"
  croz-internal:
    npmRegistryServer: "https://nexus.croz.net/repository/npm/"
