module.exports = {
  projects: [
    "<rootDir>/apps/example",
    "<rootDir>/libs/alert",
    "<rootDir>/libs/core",
    "<rootDir>/libs/data-display",
    "<rootDir>/libs/date",
    "<rootDir>/libs/dev",
    "<rootDir>/libs/form-elements",
    "<rootDir>/libs/form-elements-advanced",
    "<rootDir>/libs/formik-elements",
    "<rootDir>/libs/icons",
    "<rootDir>/libs/intl",
    "<rootDir>/libs/menu",
    "<rootDir>/libs/patterns",
    "<rootDir>/libs/selectors",
    "<rootDir>/storybook",
    "<rootDir>/libs/theme",
    "<rootDir>/libs/upload",
    "<rootDir>/libs/util",
  ],
};
