name: Build

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build all libs together
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build all modules
        run: yarn build

      - name: Build Storybook
        run: yarn run build-storybook

      - name: Upload Storybook Artifact
        uses: actions/upload-artifact@v2
        with:
          name: storybook
          path: dist/storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          token: ${{ github.token }}
          publish_dir: dist/storybook
          publish_branch: main
