name: Build

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build all libs together
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node lts
        uses: actions/setup-node@v4
        with:
          node-version: 16.17.1
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build all modules
        run: yarn build

      - name: Build storybook
        run: yarn run build-storybook

      - name: Fix permissions
        run: |
            chmod -c -R +rX "dist/storybook/" | while read line; do
              echo "::warning title=Invalid file permissions automatically fixed::$line"
            done

      - name: Compress artifacts
        run: tar -zcvf github-pages.tar.gz dist/storybook

      - name: Upload storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist/storybook
  deploy:
    runs-on: ubuntu-latest
    name: Publish Storybook
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}
          artifact_name: github-pages