name: Build

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build all libs together
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node lts
        uses: actions/setup-node@v4
        with:
          node-version: 16.17.1
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build all modules
        run: yarn build

      - name: Build storybook
        run: yarn run build-storybook

      - name: Upload storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist/storybook
  deploy:
    runs-on: ubuntu-latest
    name: Publish Storybook
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
        id: download-artifact

      - name: Get artifact metadata
        run: |
          echo "::set-output name=artifact_id::$(jq -r '.metadata.id' ${{ steps.download-artifact.outputs.download_path }}/metadata.json)"
          echo "::set-output name=pages_build_version::$(jq -r '.metadata.pages_build_version' ${{ steps.download-artifact.outputs.download_path }}/metadata.json)"
        shell: bash
        id: get-artifact-metadata
        env:
          DOWNLOAD_PATH: ${{ steps.download-artifact.outputs.download_path }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_id: ${{ steps.get-artifact-metadata.outputs.artifact_id }}
          pages_build_version: "${{ steps.get-artifact-metadata.outputs.pages_build_version }}"