name: Build

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build all libs together
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup Node lts
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build all modules
        run: yarn build

      - name: Build storybook
        run: yarn run build-storybook

      - name: Upload storybook artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/storybook
  deploy:
    runs-on: ubuntu-latest
    name: Build to Storybook
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Test artifact download
        run: ls -R

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ github.token }}
          folder: dist/storybook